/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "customers" CASCADE;

CREATE TABLE "customers" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" character varying(64) NOT NULL);

