/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "orders" CASCADE;

DROP TABLE IF EXISTS "products" CASCADE;

DROP TABLE IF EXISTS "customers" CASCADE;

CREATE TABLE "customers" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL);

CREATE TABLE "products" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL);

CREATE TABLE "orders" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "customer_id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "sum" DOUBLE PRECISION NOT NULL,
  "date" timestamp NOT NULL DEFAULT 'CURRENT_TIMESTAMP');

